//! Slash commands for TUI menu and Reedline completion (single source of truth).

pub const SLASH_COMMANDS: &[&str] = &[
    "/help",
    "/keymaps",
    "/keymap",
    "/status",
    "/context",
    "/session-name",
    "/rename",
    "/usage",
    "/delete",
    "/fork",
    "/side",
    "/approve",
    "/agent",
    "/plan",
    "/goals",
    "/review",
    "/fix",
    "/test",
    "/skills",
    "/memory",
    "/compact",
    "/compact --preview",
    "/models",
    "/mcp",
    "/agents",
    "/logs",
    "/attach",
    "/image",
    "/config",
    "/connect",
    "/doctor",
    "/provider",
    "/login",
    "/logout",
    "/auth",
    "/editor",
    "/set-editor",
    "/settings",
    "/theme",
    "/personality",
    "/statusline",
    "/title",
    "/raw",
    "/mention",
    "/hooks",
    "/permissions",
    "/permission-bypass",
    "/sessions",
    "/sessions-clean",
    "/init",
    "/ide",
    "/import",
    "/feedback",
    "/new",
    "/export",
    "/thinking",
    "/stop",
    "/run-bg",
    "/ps",
    "/input",
    "/exit",
    "/quit",
    "/q",
    "/clear",
    "/clear --keep-context",
    "/undo",
    "/redo",
    "/diff",
    "/copy",
    "/transcript",
    "/cost",
    "/stats",
    "/auto-answer",
    "/retry",
    "/run",
    "/web",
    "/commit",
    "/map",
    "/history",
    "/cd",
    "/effort",
    "/project",
    "/project add",
    "/project list",
    "/project switch",
];

/// One-line description for a slash command, shown in the popup (Codex-style
/// `/command - description`). Falls back to empty for unknown commands.
pub fn slash_command_description(command: &str) -> &'static str {
    match command {
        "/help" => "show interactive help",
        "/keymaps" => "show keyboard shortcuts",
        "/keymap" => "bind a custom key to a global action",
        "/status" => "session config + token usage",
        "/context" => "session context with recent turns",
        "/session-name" => "show or set the session name",
        "/rename" => "rename the current session",
        "/usage" => "token usage, cost, and context gauge",
        "/delete" => "delete this session and start fresh",
        "/fork" => "fork the conversation into a new session",
        "/side" => "start an ephemeral side conversation (/side end to return)",
        "/approve" => "allow the most recently requested tool for this session",
        "/agent" => "switch the active agent profile",
        "/plan" => "make a step-by-step plan before coding",
        "/goals" => "show the agent's current task plan (goal tracking)",
        "/review" => "review current changes for issues",
        "/fix" => "diagnose and fix an issue",
        "/test" => "run tests / validation",
        "/skills" => "browse and use skills",
        "/memory" => "view or edit persistent memory",
        "/compact" => "summarize context to free tokens",
        "/compact --preview" => "preview the compaction summary",
        "/models" => "browse and select a model",
        "/mcp" => "list configured MCP tools",
        "/agents" => "open the agent profile picker",
        "/logs" => "show session event log",
        "/attach" => "attach a file or image",
        "/image" => "stage an image for the next message",
        "/config" => "show effective configuration",
        "/connect" => "connect an LLM provider",
        "/doctor" => "diagnose setup problems",
        "/provider" => "switch or connect a provider",
        "/login" => "log in to a provider (OAuth)",
        "/logout" => "log out of a provider",
        "/auth" => "show auth/login status",
        "/editor" => "open the external editor",
        "/set-editor" => "set the external editor command",
        "/settings" => "show workspace settings",
        "/theme" => "choose a color theme",
        "/personality" => "set the assistant's communication style",
        "/statusline" => "toggle which items show in the status bar",
        "/title" => "set the terminal window title",
        "/raw" => "raw scrollback view for copy",
        "/mention" => "mention a file with @",
        "/hooks" => "view configured lifecycle hooks",
        "/permissions" => "choose the permission mode",
        "/permission-bypass" => "toggle bypass-permissions mode",
        "/sessions" => "browse and resume saved sessions",
        "/sessions-clean" => "delete empty saved sessions",
        "/init" => "create .dcode.toml + instructions",
        "/ide" => "pull editor selection/open files into context",
        "/import" => "import Claude Code CLAUDE.md (or /import chats)",
        "/feedback" => "report a bug or request a feature",
        "/new" => "start a new chat",
        "/export" => "export the conversation to a file",
        "/thinking" => "toggle extended thinking",
        "/stop" => "cancel the turn / stop a background job",
        "/run-bg" => "run a shell command in the background",
        "/ps" => "list background jobs",
        "/input" => "send a line (e.g. a password) to an interactive session",
        "/exit" | "/quit" | "/q" => "exit dcode-ai",
        "/clear" => "clear the screen and start fresh",
        "/clear --keep-context" => "clear the screen, keep context",
        "/undo" => "undo the last turn",
        "/redo" => "redo the last undone turn",
        "/diff" => "show git diff (incl. untracked)",
        "/copy" => "copy the last response as markdown",
        "/transcript" => "full-screen transcript (scroll/expand)",
        "/cost" => "token cost for this session",
        "/stats" => "session statistics",
        "/auto-answer" => "auto-accept the suggested answer",
        "/retry" => "retry the last request",
        "/run" => "run a shell command and add output",
        "/web" => "fetch a URL or search the web into context",
        "/commit" => "stage and commit changes",
        "/map" => "show the workspace file tree",
        "/history" => "search composer history",
        "/cd" => "change the shell directory",
        "/effort" => "set reasoning effort level",
        "/project" | "/project list" | "/project switch" => "switch between connected projects",
        "/project add" => "add a project directory",
        _ => "",
    }
}
